version: "3"
volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  node_modules_backend:
    driver: ${VOLUMES_DRIVER}
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=Asia/Jakarta
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT}:3306"
      networks:
        - backend

  backend:
        build: ./backend
        image: skripsi-backend
        command: bash -c "pm2 start start.dev.json && pm2 logs"
        ports:
            - "3000:3000"
        volumes:
            - ./backend/app:/app
            - node_modules_backend:/app/node_modules
        depends_on:
            - mysql
        links: 
            - mysql
        networks:
            - backend
        environment:
            - PATH=/app/node_modules/pm2/bin/:${PATH}
            - JWT_SECRET_KEY=${JWT_SECRET}
        stdin_open: true
        tty: true